
server:
  port: 7001

spring:
  application:
    name: register-center-7001

  redis:
    lettuce:
      shutdown-timeout:

# nacos 单机服务器注册中心，及配置中心地址，单独从官网下载解压并运行，默认端口就是 8848
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
  config:
    server-addr: 127.0.0.1:8848

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.hyman.cloudeureka7001.FeignController: debug
#    com.hyman.xxx: OFF

# sentinel 单机服务器，单独从官网下载解压并运行，默认端口就是 8080