
spring:
  application:
    name: microservice-config-server

  rabbitmq:
    host: localhost
    port: 5672
    username: hyman
    password: hyman

  cloud:
    sentinel:
#     dashboard 服务器地址
      transport:
        dashboard: 192.168.218.128：7777
#     目前 sentinel 支持 Consul，zookeeper，redis，nacos，apollo，etcd 等数据源的扩展。用什么类型的数据源配相应的 key 即可
      datasource:
        - nacos:
            server-addr: 192.168.218.128：8848
#           方便区分不同应用的配置
            data-id: {spring.application.name}-sentinel
            group_id: DEFAULT_GROUP
#           指定配置项的内容格式，sentinel 提供了 json，xml 两种格式。如需自定义，可将值配置为 custom，并配置 converter-class 指向 converter 类
            data-type: json
#           表示数据源中的规则是哪种类型，有 flow，degrade，param-flow，gw-flow 等
            rule-type: flow




