server:
  port: 3344

spring:
  application:
#   这个名字很重要，是注册到注册中心必须用到的，也是服务发现时用到的名字。并且必须要对外显露统一的服务实例名称，不能更改。
    name: cloud-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        # sentinel 单机服务器，单独从官网下载解压并运行，默认端口就是 8080
        dashboard: localhost:8080
        # 默认 8719 端口，若被占用会自动从 8719 依次加 1 扫描，直到找到未占用的端口
        port: 8719

# 暴露所有的请求，以用于监控
management:
  endpoints:
    web:
      exposure:
        include: '*'